site_name: Morphux Documentation
pages:
    - Home: index.md
    - Introduction: Introduction.md
    - Install: Install.md
    - Package Manager: Package.md
theme: null
theme_dir: theme
repo_url: https://github.com/Morphux/Documentation
